language: ruby
rvm:
- 2.5.1
services:
- postgresql
before_install:
- gem install rails
- gem update --system
script:
- bundle install
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
